import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import BottomNav from "@/components/ui/BottomNav";
import { auth } from "@/auth";
import { ToastProvider } from "@/components/ui/ToastProvider";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check auth to conditionally render nav? 
  // It's client component so it handles active state, but maybe we hide it on login page?
  // For MVP, simplest is to show it always or check session in server component.
  const session = await auth();

  return (
    <html lang="ja">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          {children}
          {session && <BottomNav />}
        </ToastProvider>
      </body>
    </html>
  );
}
